events {}

http {
  server {
    listen 80;

    access_log /app/logs/audit.log;
    error_log  /app/logs/app.log warn;

    location / {
      proxy_pass         http://api-engine:3000;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
    }
  }
}